"""Initial migration

Revision ID: 1ef7246eff45
Revises: e12162cd64a3
Create Date: 2024-01-23 23:38:26.501272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef7246eff45'
down_revision: Union[str, None] = 'e12162cd64a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('database_credentials', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.create_foreign_key(None, 'database_schema', 'database_credentials', ['database_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'database_schema', type_='foreignkey')
    op.alter_column('database_credentials', 'password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###
