"""Initial migration

Revision ID: e12162cd64a3
Revises: 
Create Date: 2024-01-23 23:24:09.729501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e12162cd64a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('host', sa.String(length=80), nullable=True),
    sa.Column('dbname', sa.String(length=80), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('database_schema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=True),
    sa.Column('table_name', sa.String(length=80), nullable=True),
    sa.Column('column_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('database_schema')
    op.drop_table('database_credentials')
    # ### end Alembic commands ###
